GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /home/alexis/Desktop/checkpoints/training_logs/Removing_colors/(Seed 2) (bis) High_translations (10) v5/checkpoints exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name          | Type                  | Params | Mode
----------------------------------------------------------------
0 | gw_mod        | GWModule              | 6.3 M  | train
1 | selection_mod | SingleDomainSelection | 0      | train
2 | loss_mod      | GWLosses2Domains      | 6.3 M  | train
----------------------------------------------------------------
484 K     Trainable params
5.8 M     Non-trainable params
6.3 M     Total params
25.254    Total estimated model params size (MB)
43        Modules in train mode
35        Modules in eval mode
Epoch 1:  12%|█████████▏                                                                      | 28/243 [00:12<01:36,  2.23it/s, v_num=v36m]
                                                                                                                                           
Exception in thread Thread-9 (_pin_memory_loop):
Traceback (most recent call last):
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Detected KeyboardInterrupt, attempting graceful shutdown ...
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexis/miniconda3/envs/conda_no_color/lib/python3.11/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
